version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "5432:80"
    volumes:
      - ../angular-project/dist/angular-project/browser:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      